### ISSUE TITLE
Currently focused buffer is closed instead of OAS Info buffer

### ISSUE THREAD

**Issue by gKits** [rusagaib/oas-preview.nvim#2]
When I start a preview the info buffer opens in split mode (as expected) and I can use the preview inside my browser without any issues.  
Now when I want to do some changes while having the preview open I switch back to the buffer containing my `openapi.yml`. If I want to stop the preview I run `OASPreviewStop` and instead of closing the info buffer the buffer that I currently focus (buffer containing `openapi.yml`) is closed.  
This obviously isn't critical but it creates a tedious flow of either always having to reopen your closed working buffer or remembering to switch to the OAS info buffer which is sometimes not possible if you have closed it before.

**Comment by rusagaib** [comment]
oww i see., i already make a new commit, i was try to implement vim.fn.system() for background command work. pls check it out if its work as expected, also thanks for the insight pal 🍺 
[b788fda](https://github.com/rusagaib/oas-preview.nvim/commit/b788fdac064208d63b6c71b04bda7a2914df6e29)

**Comment by gKits** [comment]
Thanks for looking into it. Since `OASPreviewStart` does not open a separate buffer anymore and instead just logs the output this problem does not occur anymore.

One thing I noticed is that running `OASPreviewStart` doesn't automatically open a new tab in my browser anymore.  Maybe I'm confusing that behavior with a different plugin (maybe MarkdownPreview) since I haven't written any API specs in the last month but if I remember correctly this plugin also used to open the tab immediately when starting the preview but correct me if I'm wrong.

**Comment by rusagaib** [comment]
hi pal, ah yes it's good if it's running well now 🍻

yeah already tried MarkdownPreview hats off for iamcco 👍, its coolassplugin that easy to understand slight to the point and also works well on any device, ive tried it on wsl2 with lil adding setup but then its just works fine.. and i think that what inspired me to make this plugin.. while this required with a docker at least its feels look a like 😄

sounds good plan.. but in my personal opinion, sometimes I get distracted when I'm still typing docs or somtnig, then it automatically displays a new tab in the browser, or maybe it's just me  cuz i on small resolution display😄, or maybe I'll just make an option like "auto_open_url" with true/false conditions in M.setup() what do you think pal?

**Comment by rusagaib** [comment]
oke nvm finally i choose to implement the "auto_open_url" the default is true, so its could auto open the ui on your default browser, you could check it here [1bc0fe5](https://github.com/rusagaib/oas-preview.nvim/commit/1bc0fe58fc195cc66d3aadd852fdb82a09f22b42) 🍻
